### ISSUE TITLE
tableauwdc-2.0.latest versioning isn't "latest"

### ISSUE THREAD

**Issue by miguel-orange** [tableau/webdataconnector#121] opened 2016-10-22 16:58 UTC
Currently the most recent version is [tableauwdc 2.1.1](https://connectors.tableau.com/libs/tableauwdc-2.1.latest.js). However, users will only get the [latest minor revision 2.0.9](https://connectors.tableau.com/libs/tableauwdc-2.0.latest.js). Consider having an additional url to tableauwdc-2.latest.js which will default to the latest major revision.

If this is accepted [WDC Version](https://tableau.github.io/webdataconnector/docs/wdc_library_versions) document should be updated.

**Comment by xicubed** [comment] 2016-10-24 14:55
See my experiences from last week... https://github.com/tableau/webdataconnector/issues/119 the 2.0 line seems to be currently compatible with the Tableau that's shipping. 2.1 line seems to be for a future version of Tableau that isn't out yet.

**Comment by lbrendanl** [comment] 2016-10-31 19:00
Closing this as by design.  @miguel-orange, our goal here is that you specify at least a minor version when working with the API.  This will help your connector's reliability.

**Closed by lbrendanl** 2016-10-31 19:00 UTC
