### ISSUE TITLE
Problem with WDC tutorial

### ISSUE THREAD

**Issue by bristolcityfc** [tableau/webdataconnector#167] opened 2017-03-16 17:05 UTC
For the example shown in the WDC tutorial:

http://tableau.github.io/webdataconnector/docs/wdc_tutorial

Fetch Data fails with CORS error from earthquake.usgs.gov (below). Couldn't you just provided another example that works.

XMLHttpRequest cannot load http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson. Redirect from 'http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson' to 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access.

**Comment by jdomingu** [comment] 2017-03-16 18:29
@bristolcityfc So sorry for the trouble you've been having. It looks like the USGS recently added a CORS restriction to their endpoint. You can work around it with the proxy that we've built into the SDK though. It should work if you change the getJSON call from this:

```
 $.getJSON("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson"
```

to this:

```
 $.getJSON("http://localhost:8889/earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson"
```

(Also, note that it's http, not https.) If you want to read more about the proxy, see [Working with CORS](http://tableau.github.io/webdataconnector/docs/wdc_cors.html) in the docs. 

LMK if that works for you, and we'll get the samples and tutorial updated ASAP.

**Comment by jdomingu** [comment] 2017-03-16 22:52
Also, FYI I tried it again just now and I can't reproduce the CORS issue anymore. I'm guessing the API CORS restriction was rolled back. 

You can try it in the hosted Simulator to confirm:
<http://tableau.github.io/webdataconnector/Simulator/.

Closing this out. :)

**Closed** 2017-03-16 22:54 UTC
