### ISSUE TITLE
out of date issue with google spreadsheet web data connector

### ISSUE THREAD

**Issue by agarwalpavank** [tableau/webdataconnector#18] opened 2016-02-19 12:59 UTC
I had created a google spreadsheet and published it to web so that it becomes public.
Pulled the data into tableau using web data connector. Published the workbook. Now when I am trying to refresh the workbook, it gives me an error that it is out of date.

**Comment by lbrendanl** [comment] 2016-03-16 17:00
Hey @agarwalpavank, apologies for the delayed response.  What kind of error are you seeing? Is the error coming from Tableau Server?

**Comment by agarwalpavank** [comment] 2016-03-21 09:31
Yes, the error is coming from Tableau Server. It is not getting updated automatically and when manually refreshed, it gives an alert: workbook out of date.

**Comment by lbrendanl** [comment] 2016-03-24 17:09
Hey @agarwalpavank.  Did some investigation, the data source out of date error is unfortunately one of the most generic errors Tableau Server throws (Basically, in this scenario a catch all when something goes wrong within the web data connector).  Have you imported the web data connector to Tableau Server? If not, that is likely the cause.  This is a security mechanism so that the Server only runs trusted third party code.  Details here:  http://onlinehelp.tableau.com/v0.0/server/en-us/help.htm#datasource_wdc.htm#importing

If you've already done that, we should try finding a more detailed error message.  From Server (assuming you are admin), try going to Status -> Analysis -> Background Tasks for Extracts.  That will have a view that gives some more details about the extract failure.

**Comment by lbrendanl** [comment] 2016-06-08 18:56
I am closing Google Sheets related issues.  We are releasing a native connector to Google Sheets in Tableau 10.0.  More info here: http://www.tableau.com/about/blog/2016/5/connect-directly-your-google-sheets-tableau-10-53954

We will not be supporting the WDC version of the Google Sheets connector.  It will of course still be available for use! We will not move the hosted version as to not break existing connections, and the connector code itself will remain available.

**Closed by lbrendanl** 2016-06-08 18:56 UTC
